import { SIMULATION_PROPERTIES } from "./simulation-properties.ts";
import type { ComponentCategory, ComponentDefinition, ComponentMetadata, ComponentPinDefinition, PinDirection, PinSignal } from "./catalog.ts";

type Part = {
  id: string; name: string; manufacturer: string; variant: string; category: ComponentCategory;
  description: string; pins: string; source: string; section: string;
  supplies: ComponentMetadata["supplies"]; interfaces: string[];
  currentRatings?: ComponentMetadata["currentRatings"];
  aliases?: string[]; libraries?: ComponentMetadata["libraries"]; libraryNote?: string;
  notes?: string[]; kind?: ComponentMetadata["kind"]; model?: string;
};
const directions: Record<string, PinDirection> = { i: "input", o: "output", b: "bidirectional", p: "power", g: "power", x: "passive", n: "passive" };
const library = (name: string, repo: string, header: string) => ({ name, url: `https://github.com/${repo}`, headers: [header], note: "Hardware library reference; its C++ implementation is not executed by the browser simulator." });
const ti = (name: string) => `https://www.ti.com/lit/ds/symlink/${name}.pdf`;
const supply = (pins: string[], minVolts: number, maxVolts: number) => ({ pins, minVolts, maxVolts });

/** Tokens are in physical pin-number order. Repeated names retain distinct pads. */
function define(part: Part): ComponentDefinition {
  const tokens = part.pins.split(/\s+/);
  const names = tokens.map(token => token.split("/")[0]);
  const pins: ComponentPinDefinition[] = tokens.map((token, index) => {
    const [name, direction = "i", signal] = token.split("/");
    const repeated = names.filter(item => item === name).length > 1;
    const half = Math.ceil(tokens.length / 2);
    return {
      id: repeated ? `${name}_${index + 1}` : name,
      label: name, number: String(index + 1), direction: directions[direction],
      signals: [direction === "g" ? "ground" : direction === "p" ? "power" : (signal ?? "digital") as PinSignal],
      noConnect: direction === "n", side: index < half ? "left" : "right",
      order: index < half ? index : tokens.length - index - 1,
    };
  });
  return {
    id: part.id, displayName: part.name, category: part.category, description: part.description,
    width: 224, height: Math.max(144, Math.ceil(pins.length / 2) * 26 + 32), accent: part.category === "wireless" ? "#9778ed" : part.category === "power" ? "#e8ad53" : "#42d7bd",
    pins, properties: SIMULATION_PROPERTIES[part.id] ?? {}, defaultProperties: Object.fromEntries(Object.entries(SIMULATION_PROPERTIES[part.id] ?? {}).map(([key, p]) => [key, p.defaultValue])), simulated: !!part.model,
    symbol: part.kind === "module" ? "module" : "ic",
    simulation: {
      capability: part.model ? "simulated" : "unavailable", model: part.model,
      behavior: part.model ? "Normalized electrical model with power, control, and connected-output behavior." : "Place, wire, inspect, and export this part.",
      limitations: part.model ? "No analog timing, switching losses, current limiting, or thermal model. PWM is averaged." : "No electrical or library execution model yet. Radio traffic, sensor measurements, and battery behavior are not simulated.",
    },
    metadata: {
      manufacturer: part.manufacturer, variant: part.variant, kind: part.kind ?? "chip",
      aliases: part.aliases ?? [], interfaces: part.interfaces, supplies: part.supplies,
      currentRatings: part.currentRatings,
      groundPins: pins.filter(pin => pin.signals.includes("ground")).map(pin => pin.id),
      documentation: [{ title: `${part.name} manufacturer documentation`, url: part.source, section: part.section }],
      libraries: part.libraries ?? [], libraryNote: part.libraryNote ?? "GPIO or bus control; no bundled library execution.",
      notes: ["Schematic symbol, not a PCB footprint. Pin numbers refer to the stated package.", ...(part.notes ?? [])], verifiedOn: "2026-09-26",
    },
  };
}

const definitions: Part[] = [
  { id: "rfm95w", name: "RFM95W LoRa", manufacturer: "HopeRF", variant: "RFM95W, 16-pad module", kind: "module", category: "wireless", description: "SPI LoRa radio module; 3.3V logic.",
    pins: "GND/g MISO/o/spi MOSI/i/spi SCK/i/spi NSS/i/spi RESET/i DIO5/b GND/g ANT/b/analog GND/g DIO3/b DIO4/b VCC/p DIO0/b DIO1/b DIO2/b",
    source: "https://www.hoperf.com/uploads/RFM95W-V2.0_1695351437.pdf", section: "Sections 1.3–1.4, pp. 10–11", supplies: [supply(["VCC"], 1.8, 3.7)], interfaces: ["SPI", "LoRa"], aliases: ["SX1276", "radio"], model: "rfm95w-runtime", libraries: [library("LoRa", "sandeepmistry/arduino-LoRa", "LoRa.h")], notes: ["Use a suitable 3.3V source and level translation with 5V controllers; ANT requires an appropriate antenna."] },
  { id: "xbee-s2c-zigbee-th", name: "XBee S2C Zigbee", manufacturer: "Digi", variant: "XBee S2C Zigbee, non-PRO, 20-pin through-hole", kind: "module", category: "wireless", description: "Zigbee radio module with UART and SPI host interfaces.",
    pins: "VCC/p DOUT/b/uart DIN/b/uart DIO12/b RESET/i DIO10/b/pwm DIO11/b/pwm RESERVED/n DIO8/b GND/g DIO4/b/spi DIO7/b DIO9/b VREF/i/analog DIO5/b DIO6/b DIO3/b/spi DIO2/b/spi DIO1/b/analog DIO0/b/analog",
    source: "https://www.digi.com/resources/documentation/digidocs/pdfs/90002002.pdf", section: "Pin signals for the through-hole module, pp. 44–45", supplies: [supply(["VCC"], 2.1, 3.6)], interfaces: ["UART", "SPI", "Zigbee"], aliases: ["XBee", "802.15.4"], model: "xbee-runtime", libraries: [library("XBee-Arduino", "andrewrapp/xbee-arduino", "XBee.h")], notes: ["Radio firmware and API mode must match the hardware library. GPIO pins have alternate UART, SPI, analog, and sleep functions."] },
  ...(["bme280", "bmp280"] as const).map(id => ({ id, name: id.toUpperCase(), manufacturer: "Bosch Sensortec", variant: `${id.toUpperCase()}, LGA-8`, category: "sensors" as const, description: id === "bme280" ? "Humidity, pressure, and temperature sensor IC." : "Pressure and temperature sensor IC.",
    pins: "GND/g CSB/i/spi SDI/b/i2c SCK/i/i2c SDO/b/spi VDDIO/p GND/g VDD/p", source: `https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-${id}-ds00${id === "bme280" ? 2 : 1}.pdf`, section: id === "bme280" ? "Section 7.1, Table 35" : "Section 7.1, Table 29", supplies: [supply(["VDD"], 1.71, 3.6), supply(["VDDIO"], 1.2, 3.6)], interfaces: ["I2C", "SPI"], aliases: ["environment", "pressure", "temperature"], model: `${id}-runtime`, libraries: [library(`Adafruit ${id.toUpperCase()}`, `adafruit/Adafruit_${id.toUpperCase()}_Library`, `Adafruit_${id.toUpperCase()}.h`)], notes: ["Bare sensor IC; no onboard regulator or level shifting.", "I2C requires external pull-ups on SDI/SDA and SCK/SCL to 3.3V.", "CSB high selects I2C; SDO selects its address."] })),
  { id: "sht31-dis", name: "SHT31-DIS", manufacturer: "Sensirion", variant: "SHT31-DIS-B, DFN-8 with exposed ground pad", category: "sensors", description: "I2C humidity and temperature sensor IC.", pins: "SDA/b/i2c ADDR/i ALERT/o SCL/b/i2c VDD/p nRESET/i R/g VSS/g EP/g", source: "https://sensirion.com/media/documents/213E6A3B/63A5A569/Datasheet_SHT3x_DIS.pdf", section: "Section 3, Table 7; EP is the exposed die pad", supplies: [supply(["VDD"], 2.15, 5.5)], interfaces: ["I2C"], aliases: ["SHT31", "humidity", "temperature"], model: "sht31-runtime", libraries: [library("Adafruit SHT31", "adafruit/Adafruit_SHT31", "Adafruit_SHT31.h")] },
  { id: "dht22", name: "DHT22", manufacturer: "Aosong", variant: "DHT22 / AM2302, bare 4-pin sensor", kind: "sensor", category: "sensors", description: "Digital temperature and humidity sensor.", pins: "VDD/p DATA/b NC/n GND/g", source: "https://cdn.sparkfun.com/assets/f/7/d/9/c/DHT22.pdf", section: "Aosong manufacturer datasheet, pin assignment", supplies: [supply(["VDD"], 3.3, 6)], interfaces: ["DHT single-bus"], aliases: ["AM2302", "humidity", "temperature"], model: "dht22-runtime", libraries: [library("DHT sensor library", "adafruit/DHT-sensor-library", "DHT.h")], notes: ["DATA needs a pull-up. The DHT protocol is not Dallas 1-Wire."] },
  { id: "ds18b20", name: "DS18B20", manufacturer: "Analog Devices / Maxim", variant: "DS18B20, TO-92", kind: "sensor", category: "sensors", description: "Programmable digital temperature sensor.", pins: "GND/g DQ/b VDD/p", source: "https://www.analog.com/media/en/technical-documentation/data-sheets/ds18b20.pdf", section: "Pin configurations, TO-92 bottom view", supplies: [supply(["VDD"], 3, 5.5)], interfaces: ["1-Wire"], aliases: ["temperature", "Dallas"], model: "ds18b20-runtime", libraries: [library("DallasTemperature", "milesburton/Arduino-Temperature-Control-Library", "DallasTemperature.h")], notes: ["DQ needs a pull-up. Parasite power uses the wired VDD-to-ground and bus pull-up configuration."] },
  { id: "mpu-6050", name: "MPU-6050", manufacturer: "InvenSense / TDK", variant: "MPU-6050, QFN-24", category: "sensors", description: "Six-axis accelerometer and gyroscope IC.", pins: "CLKIN/i NC/n NC/n NC/n NC/n AUX_DA/b/i2c AUX_CL/o/i2c VLOGIC/p AD0/i REGOUT/o/analog FSYNC/i INT/o VDD/p NC/n NC/n NC/n NC/n GND/g RESV/n CPOUT/o/analog RESV/n CLKOUT/o SCL/i/i2c SDA/b/i2c", source: "https://cdn.sparkfun.com/datasheets/Components/General%20IC/PS-MPU-6000A.pdf", section: "InvenSense product specification, Section 7.1 MPU-6050 pinout, specification revision 3.1", supplies: [supply(["VDD"], 2.375, 3.46), supply(["VLOGIC"], 1.71, 3.46)], interfaces: ["I2C"], aliases: ["IMU", "accelerometer", "gyroscope"], model: "mpu6050-runtime", libraries: [library("Adafruit MPU6050", "adafruit/Adafruit_MPU6050", "Adafruit_MPU6050.h")], notes: ["Bare IC, not a GY-521 breakout. VLOGIC must not exceed VDD; follow bypass and reserved-pin instructions in the datasheet."] },
  { id: "soil-moisture-sen0193", name: "Capacitive Soil Moisture Sensor", manufacturer: "DFRobot", variant: "Gravity SEN0193, three-pin module", kind: "module", category: "sensors", description: "Capacitive soil probe with analog output.", pins: "VCC/p GND/g AOUT/o/analog", source: "https://wiki.dfrobot.com/sen0193", section: "Product specification and three-pin interface", supplies: [supply(["VCC"], 3.3, 5.5)], currentRatings: [{ label: "Operating current", maxAmps: 0.005, conditions: "Manufacturer listed operating current." }], interfaces: ["Analog"], aliases: ["soil sensor", "moisture probe", "SEN0193"], model: "soil-moisture-sen0193", libraryNote: "Read the analog output with analogRead(); no Arduino library is required.", notes: ["Moisture is a simulator scenario input mapped linearly onto the simulator's normalized ADC span. Real probe voltage and soil-specific calibration are not modeled; the displayed percentage is not volumetric water content."] },
  { id: "bh1750-sen0097", name: "BH1750 Light Sensor", manufacturer: "DFRobot", variant: "SEN0097, five-pin Gravity breakout", kind: "module", category: "sensors", description: "I2C ambient-light sensor module with selectable address.", pins: "VCC/p GND/g SCL/b/i2c SDA/b/i2c ADD/i", source: "https://wiki.dfrobot.com/sen0097/", section: "SEN0097 pinout, schematic, and specification", supplies: [supply(["VCC"], 3, 5)], interfaces: ["I2C"], aliases: ["BH1750", "lux", "ambient light", "SEN0097"], model: "bh1750-sen0097-runtime", libraries: [library("BH1750", "claws/BH1750", "BH1750.h")], notes: ["The SEN0097 breakout includes its I2C support circuitry and pull-ups. Select address 0x23 with ADD low or 0x5C with ADD high. Lux is an adjustable simulator input, not a photometric or spectral model."] },
  { id: "ssd1306-oled-128x64", name: "SSD1306 128×64 OLED", manufacturer: "DFRobot", variant: "Gravity DFR0486, 0.96-inch 4-pin I2C module", kind: "module", category: "displays", description: "Monochrome 128×64 OLED display with I2C interface.", pins: "VCC/p GND/g SCL/b/i2c SDA/b/i2c", source: "https://wiki.dfrobot.com/dfr0486/", section: "Specification and four-pin module pinout", supplies: [supply(["VCC"], 3.3, 5)], interfaces: ["I2C"], aliases: ["OLED", "128x64 OLED", "SSD1306 display"], model: "ssd1306-oled-runtime", libraries: [library("Adafruit SSD1306", "adafruit/Adafruit_SSD1306", "Adafruit_SSD1306.h")], notes: ["The breakout uses fixed I2C address 0x3C. The simulator implements text drawing and display-buffer updates; pixel graphics and optical brightness are not modeled."] },
  { id: "sn74ahct1g125", name: "SN74AHCT1G125 Buffer / Level Shifter", manufacturer: "Texas Instruments", variant: "SN74AHCT1G125DBVR, SOT-23-5", category: "logic", description: "Single non-inverting tri-state buffer with TTL-compatible input and 5 V output for 3.3 V GPIO to 5 V logic translation.", pins: "OE/i A/i GND/g Y/o VCC/p", source: "https://www.ti.com/lit/ds/symlink/sn74ahct1g125.pdf", section: "Pin configuration, recommended operating conditions, and switching characteristics", supplies: [supply(["VCC"], 4.5, 5.5)], interfaces: ["GPIO", "Logic-level translation"], aliases: ["74AHCT1G125", "AHCT level shifter", "logic level shifter", "single channel level shifter"], model: "sn74ahct1g125-runtime", libraryNote: "No software library is required. The A input is read from the connected signal and Y reproduces that signal at the powered logic level when active-low OE is enabled.", notes: ["OE is active low. With VCC at 4.5–5.5 V, the AHCT input recognizes a 3.3 V MCU high; share ground with the MCU and load. The browser models a non-inverting digital buffer, not propagation delay or output drive current."] },
  { id: "ws2812b-strip-8", name: "WS2812B LED Strip · 8 pixels", manufacturer: "Worldsemi", variant: "Eight daisy-chained WS2812B-V5/W 5050 pixels, 5V strip segment", kind: "module", category: "outputs", description: "Individually addressable RGB LED strip with a single-wire data input.", pins: "VDD/p DOUT/o GND/g DIN/i", source: "https://world-semi.com/web/userfiles/productfile/WS2812B_V5WDatasheet_V6.1_EN.pdf", section: "Pin function and cascade wiring; electrical characteristics and data protocol", supplies: [supply(["VDD"], 4.5, 5.5)], currentRatings: [{ label: "LED channel current", maxAmps: 0.012, conditions: "Worldsemi WS2812B family table, typical per RGB channel. Eight full-white pixels can draw up to about 0.288 A; the simulator does not solve strip current." }], interfaces: ["GPIO", "Single-wire RGB"], aliases: ["NeoPixel", "addressable RGB", "WS2812", "WS2812B", "WS2812B LED strip", "RGB strip"], model: "ws2812b-strip-8-runtime", libraries: [library("Adafruit NeoPixel", "adafruit/Adafruit_NeoPixel", "Adafruit_NeoPixel.h")], notes: ["Pixel updates are staged until show(). The browser models colors and the data connection, not 800 kHz waveforms, brightness optics, or wire-level timing."] },
  { id: "ky-040", name: "KY-040 Rotary Encoder", manufacturer: "Joy-IT", variant: "COM-KY040RE, five-pin rotary encoder module", kind: "module", category: "inputs", description: "Quadrature rotary encoder with an integrated momentary push switch.", pins: "CLK/o DT/o SW/o VCC/p GND/g", source: "https://sensorkit.joy-it.net/en/sensors/ky-040", section: "KY-040 pin assignment and rotary encoder Arduino example", supplies: [supply(["VCC"], 4.75, 5.25)], interfaces: ["GPIO", "Quadrature", "Digital input"], aliases: ["rotary encoder", "incremental encoder", "KY040", "encoder knob"], model: "ky-040-runtime", libraries: [library("Encoder", "PaulStoffregen/Encoder", "Encoder.h")], notes: ["Encoder position and push state are interactive simulator inputs. CLK/DT expose the corresponding quadrature phase; SW is active-low. The module uses 5V supply; check the target MCU's input tolerance before wiring 5V logic."] },
  { id: "keypad-4x4", name: "4×4 Matrix Keypad", manufacturer: "Generic membrane keypad", variant: "Passive 8-line matrix keypad, four rows and four columns", kind: "module", category: "inputs", description: "Sixteen-key passive matrix keypad for GPIO scanning.", pins: "R1/b R2/b R3/b R4/b C1/b C2/b C3/b C4/b", source: "https://github.com/Chris--A/Keypad", section: "Keypad library pin matrix and four-row/four-column example", supplies: [], interfaces: ["GPIO", "4×4 matrix"], aliases: ["matrix keypad", "16-key keypad", "4x4 keypad"], model: "keypad-4x4-runtime", libraries: [library("Keypad", "Chris--A/Keypad", "Keypad.h")], notes: ["This is a passive switch matrix, not an independently powered module. Connector order varies by vendor; the symbol uses explicit R1–R4 and C1–C4 labels, so map the cable to those row and column signals."] },
  { id: "relay-module-1ch-active-low", name: "5V 1-Channel Relay Module", manufacturer: "ShillehTek", variant: "1-channel opto-coupled 5V board with SRD-05VDC-SL-C relay, active-low IN", kind: "module", category: "outputs", description: "Active-low GPIO input switches a SPDT COM/NO/NC dry-contact output.", pins: "VCC/p GND/g IN/i NO/b COM/b NC/b", source: "https://shillehtek.com/blogs/shillehtek-product-manuals/1-channel-5v-relay-module-manual", section: "Specifications, pinout, wiring, and active-low Arduino example", supplies: [supply(["VCC"], 4.75, 5.25)], currentRatings: [{ label: "Contact rating", maxAmps: 10, conditions: "Manufacturer maximum 10 A at up to 30 VDC or 250 VAC. The simulator only switches dry contacts; it does not enforce ratings or model isolation." }], interfaces: ["GPIO", "SPDT relay contact"], aliases: ["relay", "active-low relay", "SPDT", "SRD-05VDC-SL-C"], model: "relay-module-1ch-runtime", notes: ["IN LOW energizes the coil and connects COM to NO. IN HIGH releases it and connects COM to NC. Floating IN has no deterministic contact state in the simulator."] },
  { id: "ds3231-rtc", name: "DS3231 Real-Time Clock", manufacturer: "Adafruit", variant: "Precision RTC Breakout #3013, DS3231 with CR1220 backup holder", kind: "module", category: "sensors", description: "Battery-backed I2C real-time clock with optional square-wave and 32 kHz outputs.", pins: "VCC/p GND/g SDA/b/i2c SCL/b/i2c BAT/p 32K/o SQW/o RST/o", source: "https://learn.adafruit.com/adafruit-ds3231-precision-rtc-breakout/pinouts", section: "Pinouts and DS3231 RTC breakout pin descriptions", supplies: [supply(["VCC"], 2.3, 5.5)], interfaces: ["I2C", "GPIO"], aliases: ["RTC", "clock", "DS3231", "date time"], model: "ds3231-rtc-runtime", libraryNote: "Use the registered Wire.h byte/register adapter at I2C address 0x68. The RTClib DateTime object API is not part of this simulator subset.", notes: ["The module has I2C pull-ups to VCC and accepts 2.3–5.5 V. The simulator advances its UTC clock from editable start fields on simulated time and models the DS3231 time/date registers; it does not model oscillator drift, leap seconds, or coin-cell discharge."] },
  { id: "micro-sd-spi-module", name: "MicroSD SPI Breakout", manufacturer: "Adafruit", variant: "MicroSD Breakout #254 with 3.3V regulator and SPI level shifter", kind: "module", category: "storage", description: "SPI microSD card module with a simulated FAT-style file store.", pins: "VIN/p GND/g CLK/i/spi DO/o/spi DI/i/spi CS/i/spi CD/o", source: "https://learn.adafruit.com/adafruit-micro-sd-breakout-board-card-tutorial/arduino-wiring", section: "Arduino wiring, module regulator and level shifter, SPI pin connections, and card detect", supplies: [supply(["VIN"], 3, 6)], interfaces: ["SPI", "File storage"], aliases: ["SD card", "micro SD", "microSD", "storage"], model: "micro-sd-spi-runtime", libraries: [library("Arduino SD", "arduino-libraries/SD", "SD.h")], libraryNote: "Registered Arduino SD.h subset: begin(cs), open(path, FILE_READ/FILE_WRITE), exists/remove, and File read/write/print/println/seek/close. The simulator stores file bytes in the virtual card; it does not execute arbitrary FAT or SD commands.", notes: ["CLK, DO, and DI are SPI SCK, MISO, and MOSI. CS may use any supported digital output. The breakout accepts VIN 3–6 V and level-shifts 3.3 V card logic. Card detect is low when absent and high when inserted."] },
  { id: "mfrc522-rfid-module", name: "MFRC522 RFID Reader", manufacturer: "NXP Semiconductors", variant: "Common RC522 13.56 MHz SPI module with 8-pin header", kind: "module", category: "wireless", description: "SPI reader for ISO/IEC 14443A and supported MIFARE tags.", pins: "NSS/i/spi SCK/i/spi MOSI/i/spi MISO/o/spi IRQ/o GND/g RST/i VCC/p", source: "https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf", section: "SPI host interface and absolute maximum ratings; module wiring follows the registered MFRC522 Arduino example", supplies: [supply(["VCC"], 3.0, 3.6)], interfaces: ["SPI", "13.56 MHz RFID"], aliases: ["RC522", "RFID", "MIFARE", "NFC reader"], model: "mfrc522-rfid-runtime", libraries: [library("MFRC522", "miguelbalboa/rfid", "MFRC522.h")], libraryNote: "Registered MFRC522 subset: PCD_Init, PICC_IsNewCardPresent, PICC_ReadCardSerial, and PICC_HaltA. Simulated tags expose UID bytes; sector authentication and RF field physics are not modeled.", notes: ["Use 3.3 V on the common RC522 module; its SPI pins are not 5 V tolerant. The board's silk-screen SDA pin is the SPI chip-select (NSS), not I2C SDA. Select a tag and UID in simulator properties."] },
  { id: "a4988-stepper-driver", name: "A4988 Stepper Driver Carrier", manufacturer: "Pololu", variant: "A4988 Stepper Motor Driver Carrier #2128, full-step default", kind: "module", category: "motors", description: "STEP/DIR microstepping driver for a bipolar stepper motor.", pins: "EN/i MS1/i MS2/i MS3/i RST/i SLP/i STEP/i DIR/i 1B/o 1A/o 2A/o 2B/o VDD/p GND/g GND/g VMOT/p", source: "https://www.pololu.com/product/2128", section: "Power connections, control inputs, microstep-selection truth table, and carrier pinout", supplies: [supply(["VDD"], 3, 5.5), supply(["VMOT"], 8, 35)], interfaces: ["GPIO", "STEP/DIR"], aliases: ["A4988", "stepper driver", "step motor driver"], model: "a4988-stepper-runtime", notes: ["DIR selects rotation direction and each rising STEP edge advances one selected microstep. EN is active low; RST and SLP must be high to run. Unconnected MS pins use the carrier's pull-downs and select full step. The simulator does not model coil-current regulation, torque, heating, or missed steps."] },
  { id: "bipolar-stepper-motor", name: "Bipolar Stepper Motor", manufacturer: "Pololu", variant: "NEMA 17 bipolar stepper, 200 full steps per revolution", kind: "module", category: "motors", description: "Four-wire bipolar stepper motor driven by two H-bridges or a STEP/DIR carrier.", pins: "1A/b 1B/b 2A/b 2B/b", source: "https://www.pololu.com/product/2268", section: "Product specifications, wiring diagram, and four-wire bipolar coil pairs", supplies: [], interfaces: ["Bipolar coils"], aliases: ["stepper motor", "NEMA 17", "bipolar motor"], model: "bipolar-stepper-runtime", notes: ["Connect coil 1 to 1A/1B and coil 2 to 2A/2B on the driver. The display follows valid driver steps; it does not model load torque, inertia, or missed steps."] },
  { id: "cd74hc4067", name: "CD74HC4067", manufacturer: "Texas Instruments", variant: "CD74HC4067M, SOIC-24", category: "multiplexers", description: "16-channel bidirectional analog multiplexer / demultiplexer.", pins: "COM/b/analog I7/b/analog I6/b/analog I5/b/analog I4/b/analog I3/b/analog I2/b/analog I1/b/analog I0/b/analog S0/i S1/i GND/g S3/i S2/i E/i I15/b/analog I14/b/analog I13/b/analog I12/b/analog I11/b/analog I10/b/analog I9/b/analog I8/b/analog VCC/p", source: ti("cd74hc4067"), section: "Section 4, pin table and truth table", supplies: [supply(["VCC"], 2, 6)], interfaces: ["GPIO", "Analog"], aliases: ["mux", "demux", "16 channel"], model: "mux-4067", notes: ["E low enables the selected channel. S0 is the least significant select bit."] },
  { id: "cd74hc4051", name: "CD74HC4051", manufacturer: "Texas Instruments", variant: "CD74HC4051E, PDIP-16", category: "multiplexers", description: "8-channel bidirectional analog multiplexer / demultiplexer.", pins: "A4/b/analog A6/b/analog COM/b/analog A7/b/analog A5/b/analog E/i VEE/g GND/g S2/i S1/i S0/i A3/b/analog A0/b/analog A1/b/analog A2/b/analog VCC/p", source: ti("cd74hc4051"), section: "Section 4, Table 4-1", supplies: [supply(["VCC"], 2, 6)], interfaces: ["GPIO", "Analog"], aliases: ["mux", "demux", "8 channel"], model: "mux-4051", notes: ["The normalized model requires VEE at ground and models single-supply operation only."] },
  { id: "74hc138", name: "74HC138", manufacturer: "Nexperia", variant: "74HC138D, SO16", category: "multiplexers", description: "3-to-8 decoder / demultiplexer with active-low outputs.", pins: "A0/i A1/i A2/i E1/i E2/i E3/i Y7/o GND/g Y6/o Y5/o Y4/o Y3/o Y2/o Y1/o Y0/o VCC/p", source: "https://assets.nexperia.com/documents/data-sheet/74HC_HCT138.pdf", section: "Sections 5–6, pin description and function table", supplies: [supply(["VCC"], 2, 6)], interfaces: ["GPIO"], aliases: ["decoder", "demux"], model: "decoder-138", notes: ["E1 and E2 low plus E3 high enable decoding. Selected output goes low."] },
  { id: "74hc595", name: "74HC595", manufacturer: "Nexperia", variant: "74HC595D, SO16", category: "logic", description: "8-bit shift register with storage register and tri-state outputs.", pins: "Q1/o Q2/o Q3/o Q4/o Q5/o Q6/o Q7/o GND/g Q7S/o MR/i SHCP/i STCP/i OE/i DS/i Q0/o VCC/p", source: "https://assets.nexperia.com/documents/data-sheet/74HC_HCT595.pdf", section: "Section 6.2, Table 2", supplies: [supply(["VCC"], 2, 6)], interfaces: ["GPIO", "Serial shift"], aliases: ["shift register", "IO expansion"], model: "74hc595-runtime" },
  { id: "mcp23017", name: "MCP23017", manufacturer: "Microchip", variant: "MCP23017, 28-pin SPDIP", category: "multiplexers", description: "16-bit I2C GPIO expander with interrupt outputs.", pins: "GPB0/b GPB1/b GPB2/b GPB3/b GPB4/b GPB5/b GPB6/b GPB7/b VDD/p VSS/g NC/n SCL/i/i2c SDA/b/i2c NC/n A0/i A1/i A2/i RESET/i INTB/o INTA/o GPA0/b GPA1/b GPA2/b GPA3/b GPA4/b GPA5/b GPA6/b GPA7/b", source: "https://ww1.microchip.com/downloads/en/devicedoc/20001952c.pdf", section: "28-pin MCP23017 pin diagram and Table 2-1", supplies: [supply(["VDD"], 1.8, 5.5)], interfaces: ["I2C", "GPIO"], aliases: ["IO expander"], model: "mcp23017-runtime", libraries: [library("Adafruit MCP23017", "adafruit/Adafruit-MCP23017-Arduino-Library", "Adafruit_MCP23X17.h")] },
  { id: "tca9548a", name: "TCA9548A", manufacturer: "Texas Instruments", variant: "TCA9548APW, TSSOP-24", category: "multiplexers", description: "Eight-channel I2C bus switch.", pins: "A0/i A1/i RESET/i SD0/b/i2c SC0/b/i2c SD1/b/i2c SC1/b/i2c SD2/b/i2c SC2/b/i2c SD3/b/i2c SC3/b/i2c GND/g SD4/b/i2c SC4/b/i2c SD5/b/i2c SC5/b/i2c SD6/b/i2c SC6/b/i2c SD7/b/i2c SC7/b/i2c A2/i SCL/b/i2c SDA/b/i2c VCC/p", source: ti("tca9548a"), section: "Section 4, PW package", supplies: [supply(["VCC"], 1.65, 5.5)], interfaces: ["I2C"], aliases: ["I2C mux", "bus switch"], model: "tca9548a-runtime", libraries: [library("TCA9548", "RobTillaart/TCA9548", "TCA9548.h")] },
  { id: "tb6612fng", name: "TB6612FNG", manufacturer: "Toshiba", variant: "TB6612FNG, SSOP-24", category: "drivers", description: "Dual motor H-bridge with PWM and standby control.", pins: "AO1/o AO1/o PGND1/g PGND1/g AO2/o AO2/o BO2/o BO2/o PGND2/g PGND2/g BO1/o BO1/o VM2/p VM3/p PWMB/i/pwm BIN2/i BIN1/i GND/g STBY/i VCC/p AIN1/i AIN2/i PWMA/i/pwm VM1/p", source: "https://toshiba.semicon-storage.com/info/docget.jsp?did=10660&prodName=TB6612FNG", section: "Pin functions p. 2, operating range p. 3, control table p. 4", supplies: [supply(["VCC"], 2.7, 5.5), supply(["VM1", "VM2", "VM3"], 2.5, 13.5)], interfaces: ["GPIO", "PWM"], aliases: ["motor driver", "H bridge"], model: "driver-tb6612", currentRatings: [{ label: "Output per bridge", maxAmps: 1, conditions: "VM >= 4.5 V, without PWM; 0.4 A at lower VM. Operating range, datasheet p. 3. Thermal limits still apply." }], libraries: [library("SparkFun TB6612FNG", "sparkfun/SparkFun_TB6612FNG_Arduino_Library", "SparkFun_TB6612.h")], notes: ["Wire every VM and power-ground pad on hardware. Standby low disables both bridges."] },
  { id: "drv8833", name: "DRV8833", manufacturer: "Texas Instruments", variant: "DRV8833PW, TSSOP-16 (no exposed pad)", category: "drivers", description: "Dual motor H-bridge with sleep input and sense connections.", pins: "AISEN/x/analog AOUT2/o BOUT2/o BISEN/x/analog BOUT1/o nFAULT/o BIN1/i/pwm BIN2/i/pwm VCP/x/analog VM/p GND/g VINT/o/analog AIN2/i/pwm AIN1/i/pwm nSLEEP/i AOUT1/o", source: "https://www.ti.com/lit/gpn/drv8833", section: "Section 5, HTSSOP/TSSOP pin-number column", supplies: [supply(["VM"], 2.7, 10.8)], interfaces: ["GPIO", "PWM"], aliases: ["motor driver", "H bridge"], model: "driver-drv8833", currentRatings: [{ label: "RMS per bridge", maxAmps: 0.5, conditions: "PW TSSOP package, VM = 5 V, 25 C; not the 1.5 A PowerPAD package rating." }], notes: ["PW package current rating differs from PowerPAD versions. Connect each used bridge's sense pin to ground, directly or through its sense resistor. VCP and VINT need external capacitors on hardware."] },
  { id: "l298", name: "L298", manufacturer: "STMicroelectronics", variant: "L298N, Multiwatt15", category: "drivers", description: "Dual full-bridge motor driver IC with separate logic supply.", pins: "SENSE_A/x/analog OUT1/o OUT2/o VS/p IN1/i ENA/i/pwm IN2/i GND/g VSS/p IN3/i ENB/i/pwm IN4/i OUT3/o OUT4/o SENSE_B/x/analog", source: "https://www.st.com/resource/en/datasheet/l298.pdf", section: "Section 3, Multiwatt15 pin diagram and Table 3", supplies: [supply(["VSS"], 4.5, 7), supply(["VS"], 4.8, 46)], interfaces: ["GPIO", "PWM"], aliases: ["L298N", "motor driver", "H bridge"], model: "driver-l298", currentRatings: [{ label: "DC output per bridge", maxAmps: 2, conditions: "Absolute maximum; operation also constrained by dissipation and heatsinking. Not a simulated current limit." }], notes: ["Bare IC, not an L298N module. Sense returns and external flyback diodes are required on hardware."] },
  { id: "bq24074", name: "BQ24074 Charger", manufacturer: "Texas Instruments", variant: "BQ24074, RGT VQFN-16 with exposed pad", category: "power", description: "Standalone single-cell Li-ion charger with power-path management.", pins: "TS/i/analog BAT/b/analog BAT/b/analog CE/i EN2/i EN1/i PGOOD/o VSS/g CHG/o OUT/o/analog OUT/o/analog ILIM/x/analog IN/p TMR/x/analog ITERM/x/analog ISET/x/analog EP/g", source: ti("bq24074"), section: "Figure 7-2 and Table 7-1, BQ24074 column", supplies: [supply(["IN"], 4.35, 10.2)], interfaces: ["GPIO", "Analog"], aliases: ["charger", "battery", "power path"], model: "bq24074-runtime", libraryNote: "Standalone charger configured by pins and external resistors; no software library required.", notes: ["Not a complete BMS. Requires external capacitors, programming resistors, and battery temperature sensing."] },
  { id: "bq27441-g1", name: "BQ27441-G1 Fuel Gauge", manufacturer: "Texas Instruments", variant: "BQ27441DRZR-G1A, SON-12 with exposed pad", category: "power", description: "Single-cell battery fuel gauge with I2C reporting.", pins: "SDA/b/i2c SCL/b/i2c VSS/g NC/n VDD/o/analog BAT/p SRN/i/analog SRP/i/analog NC/n BIN/i NC/n GPOUT/b EP/g", source: ti("bq27441-g1"), section: "Section 7, pin functions; G1A chemistry option", supplies: [supply(["BAT"], 2.45, 4.5)], interfaces: ["I2C"], aliases: ["battery", "state of charge", "fuel gauge"], model: "bq27441-runtime", libraries: [library("SparkFun BQ27441", "sparkfun/SparkFun_BQ27441_Arduino_Library", "SparkFunBQ27441.h")], notes: ["G1A is the 4.2V chemistry variant. VDD is an internal regulator output, not a supply input. No battery chemistry is simulated."] },
  { id: "bq76920", name: "BQ76920 Battery Monitor", manufacturer: "Texas Instruments", variant: "BQ7692000, TSSOP-20", category: "power", description: "3–5 cell battery monitor and protection controller.", pins: "DSG/o CHG/o VSS/g SDA/b/i2c SCL/i/i2c TS1/i/analog CAP1/o/analog REGOUT/o/analog REGSRC/p BAT/p NC/n VC5/i/analog VC4/i/analog VC3/i/analog VC2/i/analog VC1/i/analog VC0/i/analog SRP/i/analog SRN/i/analog ALERT/b", source: ti("bq76920"), section: "Section 6.2, Table 6-1", supplies: [supply(["BAT"], 6, 25), supply(["REGSRC"], 6, 25)], interfaces: ["I2C", "Analog"], aliases: ["BMS", "battery protection", "cell balancing"], model: "bq76920-runtime", libraries: [library("bq769x0", "LibreSolar/bq769x0-arduino-library", "bq769x0.h")], notes: ["The referenced LibreSolar hardware library is archived and unmaintained; it is documentation, not bundled runtime support.", "Requires external protection FETs, cell filters, and a current sense resistor. This entry is not a complete battery protection circuit."] },
];

export const EXPANDED_COMPONENTS: Readonly<Record<string, ComponentDefinition>> = Object.freeze(Object.fromEntries(definitions.map(part => {
  const definition = define(part);
  // Exposed pads are identified by EP, rather than inventing a lead number.
  definition.pins = definition.pins.map(pin => pin.id === "EP" ? { ...pin, number: "EP" } : pin);
  return [part.id, definition];
})));
